# Generated by Django 4.1 on 2023-05-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_alter_wishlist_experience_alter_wishlist_rooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='experience',
            new_name='experiences',
        ),
    ]
